name: Sync Backend to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Backend to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend
          git init
          git config user.name "srajalt76"
          git config user.email "srajalt76@gmail.com"
          git add .
          git commit -m "Deploy updated backend from GitHub Action"
          git push --force https://srajalt76:${HF_TOKEN}@huggingface.co/spaces/srajalt76/UnLegalize-Backend HEAD:main
